/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package edu.cads.testestimation.userinterface;


import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.print.PageFormat;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.swing.*;
import javax.swing.text.DefaultFormatter;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Ari100tell
 */
public class TestEstimationFrame extends javax.swing.JFrame {
private String directoryName = System.getProperty("user.dir");
    /**
     * Creates new form TestEstimationFrame
     */
    public TestEstimationFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings({"unchecked", "null"})
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabelStatusBar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldSystemName = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPaneDate = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jspinnerNumberResult = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,100000,1));
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        MaskFormatter formatter3 = null;
        try {
            formatter3 = new MaskFormatter("##.#%");
            formatter3.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField1 = new javax.swing.JFormattedTextField(formatter3);
        MaskFormatter formatter2 = null;
        try {
            formatter2 = new MaskFormatter("##.#%");
            formatter2.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField2 = new javax.swing.JFormattedTextField(formatter2);
        MaskFormatter formatter5 = null;
        try {
            formatter5 = new MaskFormatter("##.#%");
            formatter5.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField3 = new javax.swing.JFormattedTextField(formatter5);
        MaskFormatter formatter4 = null;
        try {
            formatter4 = new MaskFormatter("##.#%");
            formatter4.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField4 = new javax.swing.JFormattedTextField(formatter4);
        MaskFormatter formatter1 = null;
        try {
            formatter1 = new MaskFormatter("##.#%");
            formatter1.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField5 = new javax.swing.JFormattedTextField(formatter1);
        MaskFormatter formatter6 = null;
        try {
            formatter6 = new MaskFormatter("##.#%");
            formatter6.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField6 = new javax.swing.JFormattedTextField(formatter6);
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jSpinnerModalResultNumber = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,100000,1));
        MaskFormatter formatter10 = null;
        try {
            formatter10 = new MaskFormatter("##.#%");
            formatter10.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField9 = new javax.swing.JFormattedTextField(formatter10);
        MaskFormatter formatter11 = null;
        try {
            formatter11 = new MaskFormatter("##.#%");
            formatter11.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField10 = new javax.swing.JFormattedTextField(formatter11);
        jDateChooser4 = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField20 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField25 = new javax.swing.JTextField();
        jSpinner1 = new javax.swing.JSpinner(new SpinnerNumberModel(0,0,1000,1));
        MaskFormatter formatter12 = null;
        try {
            formatter12 = new MaskFormatter("##.#%");
            formatter12.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField11 = new javax.swing.JFormattedTextField(formatter12);
        MaskFormatter formatter13 = null;
        try {
            formatter13 = new MaskFormatter("##.#%");
            formatter13.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField12 = new javax.swing.JFormattedTextField(formatter13);
        MaskFormatter formatter14 = null;
        try {
            formatter14 = new MaskFormatter("##.#%");
            formatter14.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField13 = new javax.swing.JFormattedTextField(formatter14);
        jDateChooser5 = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField28 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField29 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        MaskFormatter formatter7 = null;
        try {
            formatter7 = new MaskFormatter("v. ##.##");
            formatter7.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField7 = new javax.swing.JFormattedTextField(formatter7);
        MaskFormatter formatter9 = null;
        try {
            formatter9 = new MaskFormatter("##.#%");
            formatter9.setPlaceholderCharacter('_');
        } catch (java.text.ParseException exc) {
            // требуется ручное исключение
        }
        jFormattedTextField8 = new javax.swing.JFormattedTextField(formatter9);
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jFormattedTextField14 = new javax.swing.JFormattedTextField();
        jProgressBar1 = new javax.swing.JProgressBar(0,0,100);
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 0), new java.awt.Dimension(1, 32767));
        jComboBox1 = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemSave = new javax.swing.JMenuItem();
        jMenuItemSaveAs = new javax.swing.JMenuItem();
        jMenuItemSaveAll = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemOpen = new javax.swing.JMenuItem();
        jMenuOpenLast = new javax.swing.JMenu();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPrint = new javax.swing.JMenuItem();
        jMenuItemSavingOptions = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuView = new javax.swing.JMenu();
        jMenuWindow = new javax.swing.JMenu();
        jCheckBoxMenuItemStatusBar = new javax.swing.JCheckBoxMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jCheckBoxMenuItemWorkData = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemEstimationResults = new javax.swing.JCheckBoxMenuItem();
        jMenuStyle = new javax.swing.JMenu();
        jRadioButtonMenuItemClassic = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemMetallic = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemNimbus = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemMotif = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItemWindows = new javax.swing.JRadioButtonMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemResetOptions = new javax.swing.JMenuItem();
        jMenuData = new javax.swing.JMenu();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItem20 = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenu29 = new javax.swing.JMenu();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenu28 = new javax.swing.JMenu();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItemViewOptions = new javax.swing.JMenuItem();
        jMenuResult = new javax.swing.JMenu();
        jMenuItemCalculate = new javax.swing.JMenuItem();
        jMenuItemEstimate = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItemClear = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelp = new javax.swing.JMenuItem();
        jMenuItemReportBug = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItemCheckUpdating = new javax.swing.JMenuItem();
        jMenuItemDocumentation = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAboutProgram = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelStatusBar.setText("Рядок стану");
        jLabelStatusBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Назва тестуємої системи");

        jTextFieldSystemName.setDocument(new JTextFieldFilter(JTextFieldFilter.ALPHA));
        jTextFieldSystemName.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jspinnerNumberResult.setToolTipText("Оберіть номер спику результатів [0;100000]");
        JSpinner.NumberEditor jsEditor = (JSpinner.NumberEditor)jspinnerNumberResult.getEditor();
        DefaultFormatter formatter = (DefaultFormatter) jsEditor.getTextField().getFormatter();
        formatter.setAllowsInvalid(false);
        jspinnerNumberResult.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel9.setText("Номер списку результатів");

        jLabel11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel11.setText("Загальна кількість багів");

        JTextFieldFilter jTextFieldFilter = new JTextFieldFilter(JTextFieldFilter.NUMERIC);
        jTextFieldFilter.setLimitLength(5);
        jTextField9.setDocument(jTextFieldFilter);
        jTextField9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel12.setText("Кількість виправлених багів");

        JTextFieldFilter jTextFieldFilter1 = new JTextFieldFilter(JTextFieldFilter.NUMERIC);
        jTextFieldFilter1.setLimitLength(5);
        jTextField11.setDocument(jTextFieldFilter1);
        jTextField11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel13.setText("Оцінка юзабіліті");

        jLabel14.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel14.setText("Навантажувальне тестування");

        jLabel15.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel15.setText("Оцінка UI");

        jLabel16.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel16.setText("Оцінка сумісності");

        jLabel17.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel17.setText("Оцінка безпеки");

        jLabel18.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel18.setText("Оцінка продуктивності");

        jFormattedTextField1.setText("jFormattedTextField1");
        jFormattedTextField1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jFormattedTextField2.setText("jFormattedTextField1");
        jFormattedTextField2.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jFormattedTextField3.setText("jFormattedTextField1");
        jFormattedTextField3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jFormattedTextField4.setText("jFormattedTextField1");
        jFormattedTextField4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jFormattedTextField5.setText("jFormattedTextField1");
        jFormattedTextField5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jFormattedTextField6.setText("jFormattedTextField1");
        jFormattedTextField6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField3)
                    .addComponent(jFormattedTextField4)
                    .addComponent(jFormattedTextField1)
                    .addComponent(jFormattedTextField2)
                    .addComponent(jTextField11)
                    .addComponent(jspinnerNumberResult)
                    .addComponent(jTextField9)
                    .addComponent(jFormattedTextField5))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jspinnerNumberResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jFormattedTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel15)
                    .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jFormattedTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPaneDate.addTab("Дані системного тестування", jPanel5);

        jPanel1.setPreferredSize(new java.awt.Dimension(248, 391));

        jLabel1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel1.setText("Номер списку результатів");

        jLabel3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel3.setText("Загальна кількість багів");

        jLabel4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel4.setText("Оцінка регресійного тестування");

        jLabel5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel5.setText("Кількість мок-об'єктів");

        jLabel6.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel6.setText("Покриття модульними тестами");

        jLabel7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel7.setText("Кількість виправлених багів");

        jLabel8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel8.setText("Дата завершення тестування");

        JTextFieldFilter jTextFieldFilter3 = new JTextFieldFilter(JTextFieldFilter.NUMERIC);
        jTextFieldFilter3.setLimitLength(5);
        jTextField3.setDocument(jTextFieldFilter3);
        jTextField3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        JTextFieldFilter jTextFieldFilter8 = new JTextFieldFilter(JTextFieldFilter.NUMERIC);
        jTextFieldFilter8.setLimitLength(4);
        jTextField5.setDocument(jTextFieldFilter8);
        jTextField5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        JTextFieldFilter jTextFieldFilter2 = new JTextFieldFilter(JTextFieldFilter.NUMERIC);
        jTextFieldFilter2.setLimitLength(9);
        jTextField7.setDocument(jTextFieldFilter2);
        jTextField7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        JSpinner.NumberEditor jsEditorModalResult = (JSpinner.NumberEditor)jSpinnerModalResultNumber.getEditor();
        DefaultFormatter formatterModalResult = (DefaultFormatter) jsEditorModalResult.getTextField().getFormatter();
        formatterModalResult.setAllowsInvalid(false);
        jSpinnerModalResultNumber.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jSpinnerModalResultNumber.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinnerModalResultNumber, ""));
        jSpinnerModalResultNumber.setRequestFocusEnabled(false);

        jFormattedTextField9.setText("jFormattedTextField9");
        jFormattedTextField9.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jFormattedTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField9ActionPerformed(evt);
            }
        });

        jFormattedTextField10.setText("jFormattedTextField10");
        jFormattedTextField10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jDateChooser4.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField9)
                    .addComponent(jFormattedTextField10)
                    .addComponent(jSpinnerModalResultNumber)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jSpinnerModalResultNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jFormattedTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jDateChooser4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPaneDate.addTab("Дані модульного тестування", jPanel1);

        jLabel19.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel19.setText("Номер звіту впровадження");

        jLabel20.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel20.setText("Дата створення звіту");

        jLabel21.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel21.setText("Загальна кількість багів");

        JTextFieldFilter jTextFieldFilter9 = new JTextFieldFilter(JTextFieldFilter.NUMERIC);
        jTextFieldFilter9.setLimitLength(9);
        jTextField20.setDocument(jTextFieldFilter9);
        jTextField20.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel23.setText("Загальна оцінка користувача");

        jLabel24.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel24.setText("Вірогідність критичного багу");

        jLabel25.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel25.setText("Оцінка стабільності");

        jLabel26.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel26.setText("Попередный дохід");

        JTextFieldFilter jTextFieldFilter5 = new JTextFieldFilter(JTextFieldFilter.NUMERIC);
        jTextFieldFilter5.setLimitLength(9);
        jTextField25.setDocument(jTextFieldFilter5);
        jTextField25.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        JSpinner.NumberEditor jsEditorIntroductionData = (JSpinner.NumberEditor)jSpinner1.getEditor();
        DefaultFormatter formatterIntroductionData = (DefaultFormatter) jsEditorIntroductionData.getTextField().getFormatter();
        formatterIntroductionData.setAllowsInvalid(false);
        jSpinner1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jSpinner1.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner1, ""));

        jFormattedTextField11.setText("jFormattedTextField11");
        jFormattedTextField11.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jFormattedTextField12.setText("jFormattedTextField12");
        jFormattedTextField12.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jFormattedTextField13.setText("jFormattedTextField11");
        jFormattedTextField13.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jDateChooser5.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                        .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jFormattedTextField12, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                    .addComponent(jFormattedTextField11, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jFormattedTextField13, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField20, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField25))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jDateChooser5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jFormattedTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(jFormattedTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jFormattedTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jTextField25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        jTabbedPaneDate.addTab("Дані впровадження", jPanel3);

        jLabel27.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel27.setText("Назва");

        jTextField1.setDocument(new JTextFieldFilter(JTextFieldFilter.ALPHA));
        jTextField1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel30.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel30.setText("Версія");

        jLabel31.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel31.setText("Дата впровадження");

        jLabel32.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel32.setText("Очікуваний прибуток");

        JTextFieldFilter jTextFieldFilter4 = new JTextFieldFilter(JTextFieldFilter.NUMERIC);
        jTextFieldFilter4.setLimitLength(9);
        jTextField28.setDocument(jTextFieldFilter4);
        jTextField28.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel33.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel33.setText("Загальна кількість багів");

        JTextFieldFilter jTextFieldFilter6 = new JTextFieldFilter(JTextFieldFilter.NUMERIC);
        jTextFieldFilter6.setLimitLength(9);
        jTextField29.setDocument(jTextFieldFilter6);
        jTextField29.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jLabel34.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel34.setText("Загальна оцінка користувачів");

        jFormattedTextField7.setText("jFormattedTextField7");
        jFormattedTextField7.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jFormattedTextField8.setText("jFormattedTextField8");
        jFormattedTextField8.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        jDateChooser3.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE))
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jFormattedTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jTextField1)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField29)
                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(jFormattedTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jTextField28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jTextField29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(jFormattedTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );

        jTabbedPaneDate.addTab("План впровадження", jPanel2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneDate)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneDate, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel10.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel10.setText("Номер");

        jLabel22.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel22.setText("Дата і час оцінювання");

        jLabel28.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel28.setText("<html>Імовірність успішного <br>\nвпровадження</html>");

        jLabel29.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel29.setText("Очікуваний прибуток");

        jLabel35.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        jLabel35.setText("Потреба впровадження");

        jTextField2.setEditable(false);

        jTextField4.setEditable(false);

        jTextField10.setEditable(false);

        jTextField12.setEditable(false);

        jFormattedTextField14.setEnabled(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel10)
                    .addComponent(jLabel29)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jTextField12)
                    .addComponent(jTextField10)
                    .addComponent(jTextField4)
                    .addComponent(jFormattedTextField14, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Результати оцінювання", jPanel4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        jProgressBar1.setValue(10);

        jComboBox1.setVisible(false);
        jComboBox1.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {

            @Override
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (jComboBox1.getEditor().getItem().toString().length() < 4) {
                    if ((Character.isDigit(c) || (c == KeyEvent.VK_BACK_SPACE) || (c == KeyEvent.VK_DELETE))) {
                        getToolkit().beep();
                        e.consume();
                    }
                } else {
                    e.consume();
                }
            }
        });
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jMenuFile.setText("Файл");

        jMenuItemSave.setText("Зберегти");
        jMenuItemSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSave);

        jMenuItemSaveAs.setText("Зберегти як...");
        jMenuItemSaveAs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSaveAsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSaveAs);

        jMenuItemSaveAll.setText("Зберегти все");
        jMenuFile.add(jMenuItemSaveAll);
        jMenuFile.add(jSeparator1);

        jMenuItemOpen.setText("Відкрити");
        jMenuItemOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOpenActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemOpen);

        jMenuOpenLast.setText("Відкрити останній");
        jMenuFile.add(jMenuOpenLast);
        jMenuFile.add(jSeparator5);

        jMenuItemPrint.setText("Друк");
        jMenuItemPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPrintActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemPrint);

        jMenuItemSavingOptions.setText("Параметри збереження");
        jMenuItemSavingOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSavingOptionsActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemSavingOptions);
        jMenuFile.add(jSeparator4);

        jMenuItemExit.setText("Вихід");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar1.add(jMenuFile);

        jMenuView.setText("Вигляд");

        jMenuWindow.setText("Вікна");

        jCheckBoxMenuItemStatusBar.setSelected(true);
        jCheckBoxMenuItemStatusBar.setText("Рядок стану");
        jCheckBoxMenuItemStatusBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemStatusBarActionPerformed(evt);
            }
        });
        jMenuWindow.add(jCheckBoxMenuItemStatusBar);
        jMenuWindow.add(jSeparator11);

        jCheckBoxMenuItemWorkData.setSelected(true);
        jCheckBoxMenuItemWorkData.setText("Робочі дані");
        jCheckBoxMenuItemWorkData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemWorkDataActionPerformed(evt);
            }
        });
        jMenuWindow.add(jCheckBoxMenuItemWorkData);

        jCheckBoxMenuItemEstimationResults.setSelected(true);
        jCheckBoxMenuItemEstimationResults.setText("Результати тестування");
        jCheckBoxMenuItemEstimationResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemEstimationResultsActionPerformed(evt);
            }
        });
        jMenuWindow.add(jCheckBoxMenuItemEstimationResults);

        jMenuView.add(jMenuWindow);

        jMenuStyle.setText("Стилі оформлення");

        jRadioButtonMenuItemClassic.setText("Класична");
        jRadioButtonMenuItemClassic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemClassicActionPerformed(evt);
            }
        });
        jMenuStyle.add(jRadioButtonMenuItemClassic);

        jRadioButtonMenuItemMetallic.setText("Металіка");
        jRadioButtonMenuItemMetallic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemMetallicActionPerformed(evt);
            }
        });
        jMenuStyle.add(jRadioButtonMenuItemMetallic);

        jRadioButtonMenuItemNimbus.setText("Німбус");
        jRadioButtonMenuItemNimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemNimbusActionPerformed(evt);
            }
        });
        jMenuStyle.add(jRadioButtonMenuItemNimbus);

        jRadioButtonMenuItemMotif.setText("Motif");
        jRadioButtonMenuItemMotif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemMotifActionPerformed(evt);
            }
        });
        jMenuStyle.add(jRadioButtonMenuItemMotif);

        jRadioButtonMenuItemWindows.setSelected(true);
        jRadioButtonMenuItemWindows.setText("Windows");
        jRadioButtonMenuItemWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItemWindowsActionPerformed(evt);
            }
        });
        jMenuStyle.add(jRadioButtonMenuItemWindows);

        jMenuView.add(jMenuStyle);
        jMenuView.add(jSeparator6);

        jMenuItemResetOptions.setText("Скинути налаштування вигляду");
        jMenuItemResetOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemResetOptionsActionPerformed(evt);
            }
        });
        jMenuView.add(jMenuItemResetOptions);

        jMenuBar1.add(jMenuView);

        jMenuData.setText("Робочі дані");

        jMenu23.setText("Плани впровадження");

        jMenuItem3.setText("Додати");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem3);

        jMenuItem5.setText("Редагувати");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem5);
        jMenu23.add(jSeparator7);

        jMenuItem4.setText("Видалити поточний план");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem4);

        jMenuData.add(jMenu23);

        jMenu22.setText("Дані впровадження");

        jMenuItem22.setText("Додати");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem22);

        jMenuItem17.setText("Імпорт");
        jMenu22.add(jMenuItem17);
        jMenu22.add(jSeparator8);

        jMenuItem20.setText("Оцінити");
        jMenu22.add(jMenuItem20);
        jMenu22.add(jSeparator9);

        jMenuItem1.setText("Редагувати");
        jMenu22.add(jMenuItem1);

        jMenuData.add(jMenu22);

        jMenu17.setText("Дані тестування");

        jMenu29.setText("Модульне тестування");

        jMenuItem23.setText("Переглянути");
        jMenu29.add(jMenuItem23);

        jMenuItem24.setText("Очистити");
        jMenu29.add(jMenuItem24);

        jMenu17.add(jMenu29);

        jMenu28.setText("Системне тестування");

        jMenuItem25.setText("Переглянути");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu28.add(jMenuItem25);

        jMenuItem28.setText("Редагувати");
        jMenu28.add(jMenuItem28);

        jMenuItem26.setText("Очистити");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu28.add(jMenuItem26);

        jMenu17.add(jMenu28);

        jMenuData.add(jMenu17);
        jMenuData.add(jSeparator13);

        jMenuItemViewOptions.setText("Налаштування");
        jMenuItemViewOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemViewOptionsActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItemViewOptions);

        jMenuBar1.add(jMenuData);

        jMenuResult.setText("Результати");

        jMenuItemCalculate.setText("Обрахувати");
        jMenuItemCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCalculateActionPerformed(evt);
            }
        });
        jMenuResult.add(jMenuItemCalculate);

        jMenuItemEstimate.setText("Оцінити");
        jMenuResult.add(jMenuItemEstimate);
        jMenuResult.add(jSeparator10);

        jMenuItem2.setText("Переглянути");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuResult.add(jMenuItem2);
        jMenuResult.add(jSeparator12);

        jMenuItem10.setText("Редагувати");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenuResult.add(jMenuItem10);

        jMenuItemClear.setText("Очистити");
        jMenuItemClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemClearActionPerformed(evt);
            }
        });
        jMenuResult.add(jMenuItemClear);

        jMenuBar1.add(jMenuResult);

        jMenuHelp.setText("Довідка");

        jMenuItemHelp.setText("Зміст довідки");
        jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemHelpActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemHelp);

        jMenuItemReportBug.setText("Повідомити про проблему");
        jMenuItemReportBug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemReportBugActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemReportBug);
        jMenuHelp.add(jSeparator3);

        jMenuItemCheckUpdating.setText("Перевірити оновлення");
        jMenuHelp.add(jMenuItemCheckUpdating);

        jMenuItemDocumentation.setText("Інтерактивна документація");
        jMenuItemDocumentation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDocumentationActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemDocumentation);
        jMenuHelp.add(jSeparator2);

        jMenuItemAboutProgram.setText("Про програму");
        jMenuItemAboutProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutProgramActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAboutProgram);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabelStatusBar, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(78, 78, 78)
                                .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldSystemName, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(317, 317, 317)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldSystemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filler2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelStatusBar)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    private void jMenuItemReportBugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemReportBugActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemReportBugActionPerformed

    private void jMenuItemAboutProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutProgramActionPerformed
        AboutFrame aboutFrame = new AboutFrame();
        aboutFrame.setVisible(true);
        
    }//GEN-LAST:event_jMenuItemAboutProgramActionPerformed

    private void jMenuItemDocumentationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDocumentationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemDocumentationActionPerformed

    private void jMenuItemOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOpenActionPerformed
     JFileChooser jFileChooser = new JFileChooser(directoryName);
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jFileChooser.setMultiSelectionEnabled(true);
        jFileChooser.setAcceptAllFileFilterUsed(false);
        jFileChooser.showOpenDialog(null);

        File[] fileForChoose = jFileChooser.getSelectedFiles();

        int i = 0;
        while (i < fileForChoose.length) {
            if (!fileForChoose[i].isFile() || !fileForChoose[i].canRead()) {
                JOptionPane.showMessageDialog(null, "Файл " + fileForChoose[i].getName() + " является каталогом, не" +
                        " доступен для чтения или не создан!", "Ошибка", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (fileForChoose != null) {
                directoryName = fileForChoose[0].getParent() + "\\";
            }
            jLabelStatusBar.setText(directoryName);
            i++;
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemOpenActionPerformed

    private void jMenuItemPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPrintActionPerformed
          try {
            String cn = UIManager.getSystemLookAndFeelClassName();
            UIManager.setLookAndFeel(cn); // Use the native L&F
        } catch (Exception cnf) {
        }
        PrinterJob job = PrinterJob.getPrinterJob();
        PrintRequestAttributeSet aset = new HashPrintRequestAttributeSet();
        PageFormat pf = job.pageDialog(aset);
        job.setPrintable(new PrintDialog(), pf);
        boolean ok = job.printDialog(aset);
        if (ok) {
            try {
                 job.print(aset);
            } catch (PrinterException ex) {
             /* The job did not successfully complete */
            }
        }
        System.exit(0);
    }//GEN-LAST:event_jMenuItemPrintActionPerformed

    private void jMenuItemSavingOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSavingOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSavingOptionsActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItemViewOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemViewOptionsActionPerformed
        OptionsFrame optionsFrame = new OptionsFrame();
        optionsFrame.setVisible(true);                
    }//GEN-LAST:event_jMenuItemViewOptionsActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalculateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCalculateActionPerformed

    private void jCheckBoxMenuItemEstimationResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemEstimationResultsActionPerformed
              if (jCheckBoxMenuItemEstimationResults.isSelected()){
         //  jTabbedPane2.setVisible(true);
           jPanel7.setVisible(true);
           jCheckBoxMenuItemWorkData.setEnabled(true);
           
       }else{
           //jTabbedPane2.setVisible(false);
           //jTabbedPane1.setVisible(true);
                  jPanel7.setVisible(false);
                  jCheckBoxMenuItemWorkData.setEnabled(false);
       }        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItemEstimationResultsActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItemSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveActionPerformed
JFileChooser jFileChooser = new JFileChooser(directoryName);
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jFileChooser.setMultiSelectionEnabled(true);
        jFileChooser.setAcceptAllFileFilterUsed(false);
        jFileChooser.showSaveDialog(null);

        File[] fileForChoose = jFileChooser.getSelectedFiles();

        int i = 0;
        while (i < fileForChoose.length) {
            if (!fileForChoose[i].isFile() || !fileForChoose[i].canRead()) {
                JOptionPane.showMessageDialog(null, "Файл " + fileForChoose[i].getName() + " является каталогом, не" +
                        " доступен для записи или не создан!", "Ошибка", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (fileForChoose != null) {
                directoryName = fileForChoose[0].getParent() + "\\";
            }
            jLabelStatusBar.setText(directoryName);
            i++;
        }       
    }//GEN-LAST:event_jMenuItemSaveActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jRadioButtonMenuItemWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemWindowsActionPerformed
         this.setVisible(false);
    this.dispose();
    try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (UnsupportedLookAndFeelException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    TestEstimationFrame testEstimationFrame = new TestEstimationFrame();
    testEstimationFrame.setVisible(true);

    testEstimationFrame.jRadioButtonMenuItemMotif.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemClassic.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemNimbus.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemWindows.setSelected(true); 
    testEstimationFrame.jRadioButtonMenuItemMetallic.setSelected(false);    
    }//GEN-LAST:event_jRadioButtonMenuItemWindowsActionPerformed

    private void jRadioButtonMenuItemMotifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemMotifActionPerformed
         this.setVisible(false);
    this.dispose();
    try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.motif.MotifLookAndFeel");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (UnsupportedLookAndFeelException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    TestEstimationFrame testEstimationFrame = new TestEstimationFrame();
    testEstimationFrame.setVisible(true);

    testEstimationFrame.jRadioButtonMenuItemMotif.setSelected(true);
    testEstimationFrame.jRadioButtonMenuItemClassic.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemNimbus.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemWindows.setSelected(false); 
    testEstimationFrame.jRadioButtonMenuItemMetallic.setSelected(false);    
    }//GEN-LAST:event_jRadioButtonMenuItemMotifActionPerformed

    private void jRadioButtonMenuItemClassicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemClassicActionPerformed
        this.setVisible(false);
    this.dispose();
    try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (UnsupportedLookAndFeelException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    TestEstimationFrame testEstimationFrame = new TestEstimationFrame();
    testEstimationFrame.setVisible(true);

    testEstimationFrame.jRadioButtonMenuItemMotif.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemClassic.setSelected(true);
    testEstimationFrame.jRadioButtonMenuItemNimbus.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemWindows.setSelected(false); 
    testEstimationFrame.jRadioButtonMenuItemMetallic.setSelected(false);    
    }//GEN-LAST:event_jRadioButtonMenuItemClassicActionPerformed

    private void jRadioButtonMenuItemMetallicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemMetallicActionPerformed
    this.setVisible(false);
    this.dispose();
    try {
        UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (UnsupportedLookAndFeelException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    TestEstimationFrame testEstimationFrame = new TestEstimationFrame();
    testEstimationFrame.setVisible(true);

    testEstimationFrame.jRadioButtonMenuItemMotif.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemClassic.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemNimbus.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemWindows.setSelected(false); 
    testEstimationFrame.jRadioButtonMenuItemMetallic.setSelected(true);    
// TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItemMetallicActionPerformed

    private void jRadioButtonMenuItemNimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItemNimbusActionPerformed
         this.setVisible(false);
    this.dispose();
    try {
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    } catch (UnsupportedLookAndFeelException ex) {
        Logger.getLogger(TestEstimationFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
    TestEstimationFrame testEstimationFrame = new TestEstimationFrame();
    testEstimationFrame.setVisible(true);

    testEstimationFrame.jRadioButtonMenuItemMotif.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemClassic.setSelected(false);
    testEstimationFrame.jRadioButtonMenuItemNimbus.setSelected(true);
    testEstimationFrame.jRadioButtonMenuItemWindows.setSelected(false); 
    testEstimationFrame.jRadioButtonMenuItemMetallic.setSelected(false);    
    }//GEN-LAST:event_jRadioButtonMenuItemNimbusActionPerformed

    private void jCheckBoxMenuItemStatusBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemStatusBarActionPerformed
       if (jCheckBoxMenuItemStatusBar.isSelected()){
           jLabelStatusBar.setVisible(true);
           
       }else{
           jLabelStatusBar.setVisible(false);
       }
           
           
        
    }//GEN-LAST:event_jCheckBoxMenuItemStatusBarActionPerformed

    private void jCheckBoxMenuItemWorkDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemWorkDataActionPerformed
              if (jCheckBoxMenuItemWorkData.isSelected()){
          // jTabbedPaneDate.setVisible(true);
           jPanel6.setVisible(true);
           jCheckBoxMenuItemEstimationResults.setEnabled(true);
       }else{
                  jPanel6.setVisible(false);
                  jCheckBoxMenuItemEstimationResults.setEnabled(false);
           //jTabbedPaneDate.setVisible(false);
       }
    }//GEN-LAST:event_jCheckBoxMenuItemWorkDataActionPerformed

    private void jMenuItemSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSaveAsActionPerformed
       JFileChooser jFileChooser = new JFileChooser(directoryName);
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        jFileChooser.setMultiSelectionEnabled(true);
        jFileChooser.setAcceptAllFileFilterUsed(false);
        //jFileChooser.showSaveDialog(null);
        jFileChooser.showDialog(jLabel1, "Save As..");

        File[] fileForChoose = jFileChooser.getSelectedFiles();

        int i = 0;
        while (i < fileForChoose.length) {
            if (!fileForChoose[i].isFile() || !fileForChoose[i].canRead()) {
                JOptionPane.showMessageDialog(null, "Файл " + fileForChoose[i].getName() + " является каталогом, не" +
                        " доступен для записи или не создан!", "Ошибка", JOptionPane.ERROR_MESSAGE);
                return;
            }
            if (fileForChoose != null) {
                directoryName = fileForChoose[0].getParent() + "\\";
            }
            jLabelStatusBar.setText(directoryName);
            i++;
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSaveAsActionPerformed

    private void jFormattedTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField9ActionPerformed

    private void jMenuItemClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemClearActionPerformed
        jTextField2.setText("");
        jTextField4.setText("");
        jFormattedTextField14.setText("");
        jTextField10.setText("");
        jTextField12.setText("");
    }//GEN-LAST:event_jMenuItemClearActionPerformed

    private void jMenuItemResetOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemResetOptionsActionPerformed
        TestEstimationFrame testEstimationFrame = new TestEstimationFrame();
        testEstimationFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItemResetOptionsActionPerformed

    
 
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
 
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getImplementationPlanName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
                
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestEstimationFrame.class.getImplementationPlanName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
*/
        /* Create and display the form */        
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new TestEstimationFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemEstimationResults;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemStatusBar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemWorkData;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private com.toedter.calendar.JDateChooser jDateChooser4;
    private com.toedter.calendar.JDateChooser jDateChooser5;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField10;
    private javax.swing.JFormattedTextField jFormattedTextField11;
    private javax.swing.JFormattedTextField jFormattedTextField12;
    private javax.swing.JFormattedTextField jFormattedTextField13;
    private javax.swing.JFormattedTextField jFormattedTextField14;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JFormattedTextField jFormattedTextField5;
    private javax.swing.JFormattedTextField jFormattedTextField6;
    private javax.swing.JFormattedTextField jFormattedTextField7;
    private javax.swing.JFormattedTextField jFormattedTextField8;
    private javax.swing.JFormattedTextField jFormattedTextField9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelStatusBar;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu28;
    private javax.swing.JMenu jMenu29;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuData;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItemAboutProgram;
    private javax.swing.JMenuItem jMenuItemCalculate;
    private javax.swing.JMenuItem jMenuItemCheckUpdating;
    private javax.swing.JMenuItem jMenuItemClear;
    private javax.swing.JMenuItem jMenuItemDocumentation;
    private javax.swing.JMenuItem jMenuItemEstimate;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemOpen;
    private javax.swing.JMenuItem jMenuItemPrint;
    private javax.swing.JMenuItem jMenuItemReportBug;
    private javax.swing.JMenuItem jMenuItemResetOptions;
    private javax.swing.JMenuItem jMenuItemSave;
    private javax.swing.JMenuItem jMenuItemSaveAll;
    private javax.swing.JMenuItem jMenuItemSaveAs;
    private javax.swing.JMenuItem jMenuItemSavingOptions;
    private javax.swing.JMenuItem jMenuItemViewOptions;
    private javax.swing.JMenu jMenuOpenLast;
    private javax.swing.JMenu jMenuResult;
    private javax.swing.JMenu jMenuStyle;
    private javax.swing.JMenu jMenuView;
    private javax.swing.JMenu jMenuWindow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemClassic;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemMetallic;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemMotif;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemNimbus;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItemWindows;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JSpinner jSpinner1;
    private SpinnerNumberModel spinnerNumberModel;
    private javax.swing.JSpinner jSpinnerModalResultNumber;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPaneDate;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextFieldSystemName;
    private javax.swing.JSpinner jspinnerNumberResult;
    // End of variables declaration//GEN-END:variables
}
